# Comment use_frameworks! to accomodate for iOS 13.3.1 devices
 use_frameworks!
# use_modular_headers!

target 'CotterIOS_Example' do
  pod 'Cotter', :path => '../'

  target 'CotterIOS_Tests' do
    inherit! :search_paths

   use_frameworks!
   pod 'Nimble', '~> 8.0'
  end
end
