# Comment use_frameworks! to accomodate for iOS 13.3.1 devices
 use_frameworks!
# use_modular_headers!

target 'CotterIOS_Example' do
  pod 'TweeTextField'
  pod 'OneSignal', '2.14.3'
  pod 'Cotter', :path => '../'
  pod 'SwiftJWT'

  target 'CotterIOS_Tests' do
    inherit! :search_paths
    pod 'Nimble', '~> 8.0'
    pod 'Sourcery'
  end
end
