# Comment use_frameworks! to accomodate for iOS 13.3.1 devices
 use_frameworks!
# use_modular_headers!

target 'CotterIOS_Example' do
  pod 'TweeTextField'
  pod 'OneSignal', '2.15.3'
  pod 'Cotter', :path => '../'

  target 'CotterIOS_Tests' do
    inherit! :search_paths
    pod 'Nimble', '~> 8.0'
    pod 'Sourcery'
  end
  
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings[‘EXCLUDED_ARCHS[sdk=iphonesimulator*]’] = ‘arm64’
    end
  end
end
