name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./Source
      run: swift build -v
    - name: Run tests
      working-directory: ./Source
      run: swift test -v
