name: Swift

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Switch XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.app
    - name: Install Dependences
      run: |
        cd Example
        pod repo update
        pod install
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
      with:
        scheme: "CotterIOS-Example"
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'