name: Swift

on: [push]

jobs:
  test:
    name: build
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Dependences
      run: |
        cd Example
        pod repo update
        pod install
      shell: bash
    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/CotterIOS.xcworkspace -scheme Cotter -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty --color
      env: 
        destination: ${{ matrix.destination }}