name: Test

on: pull_request
jobs:
  test:
    runs-on: macos-10.15
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=13.7,name=iPhone 11"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Force XCode 11.7
        run: sudo xcode-select -switch /Applications/Xcode_11.7.app
      - name: Install Dependences
        run: |
          pod repo update
          pod install
        shell: bash
      - name: Build and Test
        run: |
          set -o pipefail && xcodebuild clean test -enableCodeCoverage YES -workspace Cotter.xcworkspace -scheme Cotter -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty --color
        env:
          destination: ${{ matrix.destination }}
